name = "theodll-me"
compatibility_date = "2025-12-07"
main = ".svelte-kit/cloudflare/_worker.js"

# Hinzufügen des 'site'-Blocks für SvelteKit-Assets
[site]
bucket = ".svelte-kit/cloudflare/client"
entry-point = "workers-site"